/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    pages: Page;
    'hero-images': HeroImage;
    'content-images': ContentImage;
    'seo-images': SeoImage;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    settings: Setting;
  };
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Page {
  id: string;
  content: {
    blockContent?:
      | (
          | {
              type: 'basic' | 'image';
              image?: string | HeroImage | null;
              heading: string;
              leadText?:
                | {
                    [k: string]: unknown;
                  }[]
                | null;
              links?:
                | {
                    link: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      url?: string | null;
                      label: string;
                      appearance?: ('default' | 'primary' | 'secondary') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'hero';
            }
          | {
              content: {
                [k: string]: unknown;
              }[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'richText';
            }
          | {
              image: string | ContentImage;
              includeLink?: boolean | null;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
                label: string;
                appearance?: ('default' | 'primary' | 'secondary') | null;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'image';
            }
          | {
              links?:
                | {
                    link: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?: {
                        relationTo: 'pages';
                        value: string | Page;
                      } | null;
                      url?: string | null;
                      label: string;
                      appearance?: ('default' | 'primary' | 'secondary') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'cta';
            }
          | {
              type: 'normal' | 'narrow' | 'full' | 'columns';
              content?:
                | (
                    | {
                        type: 'basic' | 'image';
                        image?: string | HeroImage | null;
                        heading: string;
                        leadText?:
                          | {
                              [k: string]: unknown;
                            }[]
                          | null;
                        links?:
                          | {
                              link: {
                                type?: ('reference' | 'custom') | null;
                                newTab?: boolean | null;
                                reference?: {
                                  relationTo: 'pages';
                                  value: string | Page;
                                } | null;
                                url?: string | null;
                                label: string;
                                appearance?: ('default' | 'primary' | 'secondary') | null;
                              };
                              id?: string | null;
                            }[]
                          | null;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'hero';
                      }
                    | {
                        content: {
                          [k: string]: unknown;
                        }[];
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'richText';
                      }
                    | {
                        image: string | ContentImage;
                        includeLink?: boolean | null;
                        link?: {
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          reference?: {
                            relationTo: 'pages';
                            value: string | Page;
                          } | null;
                          url?: string | null;
                          label: string;
                          appearance?: ('default' | 'primary' | 'secondary') | null;
                        };
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'image';
                      }
                    | {
                        links?:
                          | {
                              link: {
                                type?: ('reference' | 'custom') | null;
                                newTab?: boolean | null;
                                reference?: {
                                  relationTo: 'pages';
                                  value: string | Page;
                                } | null;
                                url?: string | null;
                                label: string;
                                appearance?: ('default' | 'primary' | 'secondary') | null;
                              };
                              id?: string | null;
                            }[]
                          | null;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'cta';
                      }
                  )[]
                | null;
              columns?:
                | {
                    widthPercent?: number | null;
                    content: (
                      | {
                          type: 'basic' | 'image';
                          image?: string | HeroImage | null;
                          heading: string;
                          leadText?:
                            | {
                                [k: string]: unknown;
                              }[]
                            | null;
                          links?:
                            | {
                                link: {
                                  type?: ('reference' | 'custom') | null;
                                  newTab?: boolean | null;
                                  reference?: {
                                    relationTo: 'pages';
                                    value: string | Page;
                                  } | null;
                                  url?: string | null;
                                  label: string;
                                  appearance?: ('default' | 'primary' | 'secondary') | null;
                                };
                                id?: string | null;
                              }[]
                            | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'hero';
                        }
                      | {
                          content: {
                            [k: string]: unknown;
                          }[];
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'richText';
                        }
                      | {
                          image: string | ContentImage;
                          includeLink?: boolean | null;
                          link?: {
                            type?: ('reference' | 'custom') | null;
                            newTab?: boolean | null;
                            reference?: {
                              relationTo: 'pages';
                              value: string | Page;
                            } | null;
                            url?: string | null;
                            label: string;
                            appearance?: ('default' | 'primary' | 'secondary') | null;
                          };
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'image';
                        }
                      | {
                          links?:
                            | {
                                link: {
                                  type?: ('reference' | 'custom') | null;
                                  newTab?: boolean | null;
                                  reference?: {
                                    relationTo: 'pages';
                                    value: string | Page;
                                  } | null;
                                  url?: string | null;
                                  label: string;
                                  appearance?: ('default' | 'primary' | 'secondary') | null;
                                };
                                id?: string | null;
                              }[]
                            | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'cta';
                        }
                    )[];
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'container';
            }
        )[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | SeoImage | null;
  };
  title?: string | null;
  summary?: string | null;
  slug?: string | null;
  editSlug?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
export interface HeroImage {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xs?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface ContentImage {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xs?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface SeoImage {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    opengraph?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Setting {
  id: string;
  defaults: {
    mainIndex?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}